import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import schoolsRouter from "./schools";
import branchesRouter from "./branches";
import gradeLevelsRouter from "./gradeLevels";
import gradesRouter from "./grades";
import classesRouter from "./classes";
import booksRouter from "./books";
import lessonsRouter from "./lessons";
import packagesRouter from "./packages";
import transactionsRouter from "./transactions";
import contentRouter from "./content";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import examScheduleRouter from "./examSchedule";
import progressChartRouter from "./progressChart";
import studentProgressRouter from "./studentProgress";
import gameScoresRouter from "./gameScores";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(schoolsRouter);
router.use(branchesRouter);
router.use(gradeLevelsRouter);
router.use(gradesRouter);
router.use(classesRouter);
router.use(booksRouter);
router.use(lessonsRouter);
router.use(packagesRouter);
router.use(transactionsRouter);
router.use(contentRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(examScheduleRouter);
router.use(progressChartRouter);
router.use(studentProgressRouter);
router.use(gameScoresRouter);

export default router;
