import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import schoolsRouter from "./schools";
import branchesRouter from "./branches";
import branchManagersRouter from "./branchManagers";
import gradeLevelsRouter from "./gradeLevels";
import gradesRouter from "./grades";
import classesRouter from "./classes";
import booksRouter from "./books";
import lessonsRouter from "./lessons";
import bookOrdersRouter from "./bookOrders";
import walletRouter from "./wallet";
import contentRouter from "./content";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import examScheduleRouter from "./examSchedule";
import progressChartRouter from "./progressChart";
import studentProgressRouter from "./studentProgress";
import consultantsRouter from "./consultants";
import consultationsRouter from "./consultations";
import gameScoresRouter from "./gameScores";
import schoolReportRouter from "./schoolReport";
import schoolTeachersRouter from "./schoolTeachers";
import studentEnrollmentsRouter from "./studentEnrollments";
import parentStudentsRouter from "./parentStudents";
import classSchedulesRouter from "./classSchedules";
import classSessionsRouter from "./classSessions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(schoolsRouter);
router.use(branchesRouter);
router.use(branchManagersRouter);
router.use(gradeLevelsRouter);
router.use(gradesRouter);
router.use(classesRouter);
router.use(booksRouter);
router.use(lessonsRouter);
router.use(bookOrdersRouter);
router.use(walletRouter);
router.use(contentRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(examScheduleRouter);
router.use(progressChartRouter);
router.use(studentProgressRouter);
router.use(consultantsRouter);
router.use(consultationsRouter);
router.use(gameScoresRouter);
router.use(schoolReportRouter);
router.use(schoolTeachersRouter);
router.use(studentEnrollmentsRouter);
router.use(parentStudentsRouter);
router.use(classSchedulesRouter);
router.use(classSessionsRouter);

export default router;
